# Generated by Django 5.2.4 on 2025-07-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('ema_email', models.EmailField(db_column='ema_email', max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Email',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('use_id', models.AutoField(db_column='use_id', primary_key=True, serialize=False)),
                ('use_name', models.CharField(db_column='use_name', max_length=100)),
                ('use_passwords', models.CharField(db_column='use_passwords', max_length=128)),
            ],
            options={
                'db_table': 'user_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User_Type',
            fields=[
                ('uset_id', models.AutoField(db_column='uset_id', primary_key=True, serialize=False)),
                ('uset_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_type',
                'managed': False,
            },
        ),
    ]
